// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/jflex/golite.flex

package com.mycompany.golite;
import com.mycompany.golite.parser.sym;
import java_cup.runtime.Symbol;
import java.util.ArrayList;
import java.util.List;


@SuppressWarnings("fallthrough")
public class GoliteLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\4\1\5\2\0\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\4\21\1\22"+
    "\1\21\1\23\3\21\1\24\1\25\1\26\1\27\1\30"+
    "\2\0\1\31\4\32\1\33\10\32\1\34\1\35\3\32"+
    "\1\36\6\32\1\37\1\40\1\41\1\0\1\32\1\0"+
    "\1\42\1\43\1\44\1\32\1\45\1\46\1\47\1\32"+
    "\1\50\1\32\1\51\1\52\1\53\1\54\1\55\1\56"+
    "\1\32\1\57\1\60\1\61\1\62\1\63\2\32\1\64"+
    "\1\32\1\65\1\66\1\67\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\2\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\1\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\12\22\1\25\1\1\1\26\1\27\1\0\1\30\1\0"+
    "\1\31\2\0\1\32\1\33\1\34\1\35\1\0\1\36"+
    "\1\0\1\37\1\40\1\41\1\42\11\22\1\43\7\22"+
    "\1\44\1\45\1\0\1\46\7\22\1\47\1\22\1\50"+
    "\1\51\5\22\1\52\1\53\1\54\2\22\1\55\2\22"+
    "\1\0\1\56\2\22\1\57\2\22\1\60\1\61\1\22"+
    "\1\62\1\22\1\0\6\22\1\0\1\22\1\63\1\22"+
    "\1\64\1\22\1\65\1\0\2\22\1\66\13\0\1\67"+
    "\4\0\1\70\3\0\1\71\4\0\1\72";

  private static int [] zzUnpackAction() {
    int [] result = new int[157];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\340\0\70\0\u0118\0\u0150"+
    "\0\70\0\70\0\70\0\u0188\0\70\0\u01c0\0\70\0\u01f8"+
    "\0\u0230\0\u0268\0\70\0\u02a0\0\u02d8\0\u0310\0\u0348\0\70"+
    "\0\70\0\u0380\0\u03b8\0\u03f0\0\u0428\0\u0460\0\u0498\0\u04d0"+
    "\0\u0508\0\u0540\0\u0578\0\70\0\u05b0\0\70\0\70\0\340"+
    "\0\70\0\u05e8\0\70\0\u0620\0\u0658\0\70\0\70\0\70"+
    "\0\70\0\u0690\0\u06c8\0\u0700\0\70\0\70\0\70\0\70"+
    "\0\u0738\0\u0770\0\u07a8\0\u07e0\0\u0818\0\u0850\0\u0888\0\u08c0"+
    "\0\u08f8\0\u0348\0\u0930\0\u0968\0\u09a0\0\u09d8\0\u0a10\0\u0a48"+
    "\0\u0a80\0\70\0\70\0\u0ab8\0\u0700\0\u0af0\0\u0b28\0\u0b60"+
    "\0\u0b98\0\u0bd0\0\u0c08\0\u0c40\0\u0348\0\u0c78\0\u0348\0\u0348"+
    "\0\u0cb0\0\u0ce8\0\u0d20\0\u0d58\0\u0d90\0\u0348\0\70\0\u0348"+
    "\0\u0dc8\0\u0e00\0\u0348\0\u0e38\0\u0e70\0\u0ea8\0\u0348\0\u0ee0"+
    "\0\u0f18\0\u0348\0\u0f50\0\u0f88\0\u0348\0\u0348\0\u0fc0\0\u0348"+
    "\0\u0ff8\0\u1030\0\u1068\0\u10a0\0\u10d8\0\u1110\0\u1148\0\u1180"+
    "\0\u11b8\0\u11f0\0\u0348\0\u1228\0\u0348\0\u1260\0\u0348\0\u1298"+
    "\0\u12d0\0\u1308\0\u0348\0\u1340\0\u1378\0\u13b0\0\u13e8\0\u1420"+
    "\0\u1458\0\u1490\0\u14c8\0\u1500\0\u1538\0\u1570\0\70\0\u15a8"+
    "\0\u15e0\0\u1618\0\u1650\0\70\0\u1688\0\u16c0\0\u16f8\0\70"+
    "\0\u1730\0\u1768\0\u17a0\0\u17d8\0\70";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[157];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\3\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\3\21"+
    "\1\22\1\23\1\24\1\25\1\26\6\27\1\30\1\2"+
    "\1\31\1\27\1\32\1\33\1\34\1\35\1\27\1\36"+
    "\3\27\1\37\2\27\1\40\1\41\1\42\1\27\1\43"+
    "\1\27\1\44\1\45\1\46\71\0\3\3\113\0\1\47"+
    "\40\0\2\50\2\0\1\50\1\51\32\50\1\52\27\50"+
    "\7\0\1\53\60\0\2\54\2\0\4\54\1\0\27\54"+
    "\1\55\27\54\14\0\1\56\12\0\1\57\56\0\1\60"+
    "\10\0\1\61\53\0\1\62\4\0\1\63\66\0\1\64"+
    "\1\0\3\21\73\0\1\65\67\0\1\66\67\0\1\67"+
    "\67\0\1\70\61\0\3\27\5\0\6\27\3\0\23\27"+
    "\24\0\3\27\5\0\6\27\3\0\13\27\1\71\1\27"+
    "\1\72\5\27\24\0\3\27\5\0\6\27\3\0\13\27"+
    "\1\73\7\27\24\0\3\27\5\0\6\27\3\0\10\27"+
    "\1\74\12\27\24\0\3\27\5\0\6\27\3\0\1\75"+
    "\7\27\1\76\1\77\1\27\1\100\4\27\1\101\2\27"+
    "\24\0\3\27\5\0\6\27\3\0\4\27\1\102\5\27"+
    "\1\103\10\27\24\0\3\27\5\0\6\27\3\0\6\27"+
    "\1\104\14\27\24\0\3\27\5\0\6\27\3\0\3\27"+
    "\1\105\14\27\1\106\2\27\24\0\3\27\5\0\6\27"+
    "\3\0\17\27\1\107\3\27\24\0\3\27\5\0\6\27"+
    "\3\0\15\27\1\110\5\27\24\0\3\27\5\0\6\27"+
    "\3\0\1\111\22\27\71\0\1\112\3\0\1\50\2\0"+
    "\1\50\32\0\1\50\16\0\1\50\1\0\1\50\16\0"+
    "\1\113\61\0\1\54\5\0\1\54\27\0\1\54\16\0"+
    "\1\54\1\0\1\54\6\0\13\62\1\114\54\62\2\63"+
    "\2\0\64\63\21\0\3\115\65\0\3\27\5\0\6\27"+
    "\3\0\13\27\1\116\7\27\24\0\3\27\5\0\6\27"+
    "\3\0\3\27\1\117\17\27\24\0\3\27\5\0\6\27"+
    "\3\0\12\27\1\120\10\27\24\0\3\27\5\0\6\27"+
    "\3\0\16\27\1\121\4\27\24\0\3\27\5\0\6\27"+
    "\3\0\10\27\1\122\12\27\24\0\3\27\5\0\6\27"+
    "\3\0\13\27\1\123\7\27\24\0\3\27\5\0\6\27"+
    "\3\0\17\27\1\124\3\27\24\0\3\27\5\0\6\27"+
    "\3\0\15\27\1\125\5\27\24\0\3\27\5\0\6\27"+
    "\3\0\12\27\1\126\10\27\24\0\3\27\5\0\6\27"+
    "\3\0\17\27\1\127\3\27\24\0\3\27\5\0\6\27"+
    "\3\0\10\27\1\130\12\27\24\0\3\27\5\0\6\27"+
    "\3\0\4\27\1\131\12\27\1\132\3\27\24\0\3\27"+
    "\5\0\6\27\3\0\12\27\1\133\10\27\24\0\3\27"+
    "\5\0\6\27\3\0\15\27\1\134\5\27\24\0\3\27"+
    "\5\0\6\27\3\0\20\27\1\135\2\27\24\0\3\27"+
    "\5\0\6\27\3\0\15\27\1\136\5\27\3\0\13\62"+
    "\1\114\4\62\1\137\47\62\21\0\3\27\5\0\6\27"+
    "\3\0\10\27\1\140\12\27\24\0\3\27\5\0\6\27"+
    "\3\0\1\141\22\27\24\0\3\27\5\0\6\27\3\0"+
    "\17\27\1\142\3\27\24\0\3\27\5\0\6\27\3\0"+
    "\3\27\1\143\17\27\24\0\3\27\5\0\6\27\3\0"+
    "\16\27\1\144\4\27\24\0\3\27\5\0\6\27\3\0"+
    "\1\145\22\27\22\0\1\146\1\0\3\27\5\0\6\27"+
    "\3\0\23\27\24\0\3\27\5\0\6\27\3\0\2\27"+
    "\1\147\20\27\24\0\3\27\5\0\6\27\3\0\10\27"+
    "\1\150\12\27\24\0\3\27\5\0\6\27\3\0\20\27"+
    "\1\151\2\27\24\0\3\27\5\0\6\27\3\0\3\27"+
    "\1\152\17\27\24\0\3\27\5\0\6\27\3\0\2\27"+
    "\1\153\3\27\1\154\14\27\24\0\3\27\5\0\6\27"+
    "\3\0\3\27\1\155\17\27\24\0\3\27\5\0\6\27"+
    "\3\0\7\27\1\156\13\27\24\0\3\27\5\0\6\27"+
    "\3\0\6\27\1\157\14\27\24\0\3\27\5\0\6\27"+
    "\3\0\3\27\1\160\17\27\24\0\3\27\5\0\6\27"+
    "\3\0\17\27\1\161\3\27\40\0\1\162\53\0\3\27"+
    "\5\0\6\27\3\0\3\27\1\163\17\27\24\0\3\27"+
    "\5\0\6\27\3\0\15\27\1\164\5\27\24\0\3\27"+
    "\5\0\6\27\3\0\13\27\1\165\7\27\24\0\3\27"+
    "\5\0\6\27\3\0\12\27\1\166\10\27\24\0\3\27"+
    "\5\0\6\27\3\0\12\27\1\167\10\27\24\0\2\27"+
    "\1\170\5\0\6\27\3\0\23\27\62\0\1\171\31\0"+
    "\3\27\5\0\6\27\3\0\2\27\1\172\20\27\24\0"+
    "\3\27\5\0\6\27\3\0\12\27\1\173\10\27\24\0"+
    "\3\27\5\0\6\27\3\0\12\27\1\174\10\27\24\0"+
    "\3\27\5\0\6\27\3\0\5\27\1\175\15\27\24\0"+
    "\3\27\5\0\6\27\3\0\20\27\1\176\2\27\24\0"+
    "\1\27\1\177\1\27\5\0\6\27\3\0\23\27\53\0"+
    "\1\200\40\0\3\27\5\0\6\27\3\0\17\27\1\201"+
    "\3\27\24\0\3\27\5\0\6\27\3\0\21\27\1\202"+
    "\1\27\24\0\3\27\5\0\6\27\3\0\3\27\1\203"+
    "\17\27\57\0\1\204\32\0\1\205\1\0\3\27\5\0"+
    "\6\27\3\0\23\27\22\0\1\206\1\0\3\27\5\0"+
    "\6\27\3\0\23\27\64\0\1\207\44\0\1\210\62\0"+
    "\1\211\3\0\1\212\104\0\1\213\101\0\1\214\64\0"+
    "\1\215\50\0\1\216\101\0\1\217\71\0\1\220\66\0"+
    "\1\221\71\0\1\222\55\0\1\223\72\0\1\224\77\0"+
    "\1\225\43\0\1\226\100\0\1\227\70\0\1\230\54\0"+
    "\1\231\106\0\1\232\72\0\1\233\54\0\1\234\106\0"+
    "\1\235\6\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[6160];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\2\1\3\11\1\1\1\11"+
    "\1\1\1\11\3\1\1\11\4\1\2\11\12\1\1\11"+
    "\1\1\2\11\1\0\1\11\1\0\1\11\2\0\4\11"+
    "\1\0\1\1\1\0\4\11\21\1\2\11\1\0\22\1"+
    "\1\11\6\1\1\0\13\1\1\0\6\1\1\0\6\1"+
    "\1\0\3\1\13\0\1\11\4\0\1\11\3\0\1\11"+
    "\4\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[157];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    // ─── Listas para reportes ──────────────────────────────────────────
    public static List<TokenReporte> listaTokens  = new ArrayList<>();
    public static List<ErrorLexico>  listaErrores = new ArrayList<>();

    /**
     * Crea el Symbol para CUP, registra el token en la lista de reporte
     * y lo retorna. Usa yyline+1 / yycolumn+1 para base-1.
     */
    private Symbol token(int tipo, Object valor) {
        int lin = yyline + 1;
        int col = yycolumn + 1;
        listaTokens.add(new TokenReporte(yytext(), SymUtils.nombreTipo(tipo), lin, col));
        return new Symbol(tipo, lin, col, valor);
    }

    private Symbol token(int tipo) {
        return token(tipo, yytext());
    }

    /** Registra un error léxico sin detener el análisis. */
    private void errorLexico() {
        int lin = yyline + 1;
        int col = yycolumn + 1;
        String msg = "El símbolo \"" + yytext() + "\" no es aceptado en el lenguaje.";
        listaErrores.add(new ErrorLexico(msg, lin, col));
        System.err.println("[Error Léxico] Línea " + lin + ", Columna " + col + ": " + msg);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public GoliteLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { errorLexico();
            }
          // fall through
          case 59: break;
          case 2:
            { /* espacios en blanco: ignorar */
            }
          // fall through
          case 60: break;
          case 3:
            { return token(sym.NOT);
            }
          // fall through
          case 61: break;
          case 4:
            { return token(sym.MOD);
            }
          // fall through
          case 62: break;
          case 5:
            { return token(sym.LPAREN);
            }
          // fall through
          case 63: break;
          case 6:
            { return token(sym.RPAREN);
            }
          // fall through
          case 64: break;
          case 7:
            { return token(sym.TIMES);
            }
          // fall through
          case 65: break;
          case 8:
            { return token(sym.PLUS);
            }
          // fall through
          case 66: break;
          case 9:
            { return token(sym.COMMA);
            }
          // fall through
          case 67: break;
          case 10:
            { return token(sym.MINUS);
            }
          // fall through
          case 68: break;
          case 11:
            { return token(sym.DOT);
            }
          // fall through
          case 69: break;
          case 12:
            { return token(sym.DIVIDE);
            }
          // fall through
          case 70: break;
          case 13:
            { return token(sym.INT_LITERAL,   Integer.parseInt(yytext()));
            }
          // fall through
          case 71: break;
          case 14:
            { return token(sym.SEMICOLON);
            }
          // fall through
          case 72: break;
          case 15:
            { return token(sym.LT);
            }
          // fall through
          case 73: break;
          case 16:
            { return token(sym.ASSIGN);
            }
          // fall through
          case 74: break;
          case 17:
            { return token(sym.GT);
            }
          // fall through
          case 75: break;
          case 18:
            { return token(sym.IDENTIFIER, yytext());
            }
          // fall through
          case 76: break;
          case 19:
            { return token(sym.LBRACKET);
            }
          // fall through
          case 77: break;
          case 20:
            { return token(sym.RBRACKET);
            }
          // fall through
          case 78: break;
          case 21:
            { return token(sym.LBRACE);
            }
          // fall through
          case 79: break;
          case 22:
            { return token(sym.RBRACE);
            }
          // fall through
          case 80: break;
          case 23:
            { return token(sym.NE);
            }
          // fall through
          case 81: break;
          case 24:
            { // Guardamos el texto sin las comillas externas
                                 String val = yytext().substring(1, yytext().length() - 1);
                                 return token(sym.STRING_LITERAL, val);
            }
          // fall through
          case 82: break;
          case 25:
            { return token(sym.AND);
            }
          // fall through
          case 83: break;
          case 26:
            { return token(sym.INC);
            }
          // fall through
          case 84: break;
          case 27:
            { return token(sym.PLUS_ASSIGN);
            }
          // fall through
          case 85: break;
          case 28:
            { return token(sym.DEC);
            }
          // fall through
          case 86: break;
          case 29:
            { return token(sym.MINUS_ASSIGN);
            }
          // fall through
          case 87: break;
          case 30:
            { /* comentario de línea: ignorar */
            }
          // fall through
          case 88: break;
          case 31:
            { return token(sym.DEFINE);
            }
          // fall through
          case 89: break;
          case 32:
            { return token(sym.LE);
            }
          // fall through
          case 90: break;
          case 33:
            { return token(sym.EQ);
            }
          // fall through
          case 91: break;
          case 34:
            { return token(sym.GE);
            }
          // fall through
          case 92: break;
          case 35:
            { return token(sym.IF);
            }
          // fall through
          case 93: break;
          case 36:
            { return token(sym.OR);
            }
          // fall through
          case 94: break;
          case 37:
            { return token(sym.RUNE_LITERAL, yytext());
            }
          // fall through
          case 95: break;
          case 38:
            { return token(sym.FLOAT_LITERAL, Double.parseDouble(yytext()));
            }
          // fall through
          case 96: break;
          case 39:
            { return token(sym.FOR);
            }
          // fall through
          case 97: break;
          case 40:
            { return token(sym.INT_TYPE);
            }
          // fall through
          case 98: break;
          case 41:
            { return token(sym.NIL);
            }
          // fall through
          case 99: break;
          case 42:
            { return token(sym.VAR);
            }
          // fall through
          case 100: break;
          case 43:
            { /* comentario bloque: ignorar  */
            }
          // fall through
          case 101: break;
          case 44:
            { return token(sym.BOOL_TYPE);
            }
          // fall through
          case 102: break;
          case 45:
            { return token(sym.ELSE);
            }
          // fall through
          case 103: break;
          case 46:
            { return token(sym.FUNC);
            }
          // fall through
          case 104: break;
          case 47:
            { return token(sym.RUNE_TYPE);
            }
          // fall through
          case 105: break;
          case 48:
            { return token(sym.BOOL_LITERAL, true);
            }
          // fall through
          case 106: break;
          case 49:
            { return token(sym.BREAK);
            }
          // fall through
          case 107: break;
          case 50:
            { return token(sym.BOOL_LITERAL, false);
            }
          // fall through
          case 108: break;
          case 51:
            { return token(sym.RETURN);
            }
          // fall through
          case 109: break;
          case 52:
            { return token(sym.STRING_TYPE);
            }
          // fall through
          case 110: break;
          case 53:
            { return token(sym.FLOAT_TYPE);
            }
          // fall through
          case 111: break;
          case 54:
            { return token(sym.CONTINUE);
            }
          // fall through
          case 112: break;
          case 55:
            { return token(sym.PRINTLN);
            }
          // fall through
          case 113: break;
          case 56:
            { return token(sym.ATOI);
            }
          // fall through
          case 114: break;
          case 57:
            { return token(sym.TYPEOF);
            }
          // fall through
          case 115: break;
          case 58:
            { return token(sym.PARSEFLOAT);
            }
          // fall through
          case 116: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
