
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.golite.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 35;
  public static final int RUNE_LITERAL = 20;
  public static final int STRING_LITERAL = 19;
  public static final int LBRACKET = 51;
  public static final int BOOL_TYPE = 14;
  public static final int GE = 43;
  public static final int UMINUS = 37;
  public static final int PLUS_ASSIGN = 28;
  public static final int LPAREN = 47;
  public static final int CONTINUE = 8;
  public static final int PRINTLN = 22;
  public static final int FOR = 6;
  public static final int MINUS = 33;
  public static final int RPAREN = 48;
  public static final int DEFINE = 27;
  public static final int SEMICOLON = 54;
  public static final int NOT = 46;
  public static final int AND = 44;
  public static final int LT = 40;
  public static final int PARSEFLOAT = 24;
  public static final int TYPEOF = 25;
  public static final int NIL = 10;
  public static final int OR = 45;
  public static final int COMMA = 53;
  public static final int INC = 30;
  public static final int ATOI = 23;
  public static final int PLUS = 32;
  public static final int ASSIGN = 26;
  public static final int IF = 4;
  public static final int DOT = 55;
  public static final int LE = 41;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int RBRACKET = 52;
  public static final int STRING_TYPE = 13;
  public static final int error = 1;
  public static final int MOD = 36;
  public static final int INT_TYPE = 11;
  public static final int BREAK = 7;
  public static final int EQ = 38;
  public static final int TIMES = 34;
  public static final int LBRACE = 49;
  public static final int ELSE = 5;
  public static final int FUNC = 3;
  public static final int RUNE_TYPE = 15;
  public static final int RBRACE = 50;
  public static final int NE = 39;
  public static final int DEC = 31;
  public static final int FLOAT_LITERAL = 18;
  public static final int GT = 42;
  public static final int FLOAT_TYPE = 12;
  public static final int VAR = 2;
  public static final int MINUS_ASSIGN = 29;
  public static final int BOOL_LITERAL = 16;
  public static final int INT_LITERAL = 17;
  public static final int IDENTIFIER = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VAR",
  "FUNC",
  "IF",
  "ELSE",
  "FOR",
  "BREAK",
  "CONTINUE",
  "RETURN",
  "NIL",
  "INT_TYPE",
  "FLOAT_TYPE",
  "STRING_TYPE",
  "BOOL_TYPE",
  "RUNE_TYPE",
  "BOOL_LITERAL",
  "INT_LITERAL",
  "FLOAT_LITERAL",
  "STRING_LITERAL",
  "RUNE_LITERAL",
  "IDENTIFIER",
  "PRINTLN",
  "ATOI",
  "PARSEFLOAT",
  "TYPEOF",
  "ASSIGN",
  "DEFINE",
  "PLUS_ASSIGN",
  "MINUS_ASSIGN",
  "INC",
  "DEC",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MOD",
  "UMINUS",
  "EQ",
  "NE",
  "LT",
  "LE",
  "GT",
  "GE",
  "AND",
  "OR",
  "NOT",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "COMMA",
  "SEMICOLON",
  "DOT"
  };
}

