
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.golite.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_DER = 48;
  public static final int Y = 44;
  public static final int LITERAL_ENTERO = 17;
  public static final int ASIGNAR = 26;
  public static final int LITERAL_FLOTANTE = 18;
  public static final int POR = 34;
  public static final int IMPRIMIR = 22;
  public static final int SI = 4;
  public static final int TIPO_RUNA = 15;
  public static final int FUNCION = 3;
  public static final int LITERAL_RUNA = 20;
  public static final int O = 45;
  public static final int DIFERENTE = 39;
  public static final int MENOS_UNARIO = 37;
  public static final int LLAVE_IZQ = 49;
  public static final int IDENTIFICADOR = 21;
  public static final int IGUAL = 38;
  public static final int SINO = 5;
  public static final int CONTINUAR = 8;
  public static final int INCREMENTO = 30;
  public static final int PUNTO_COMA = 52;
  public static final int A_ENTERO = 23;
  public static final int MENOS_ASIGNAR = 29;
  public static final int LITERAL_CADENA = 19;
  public static final int TIPO_DE = 25;
  public static final int EOF = 0;
  public static final int TIPO_ENTERO = 11;
  public static final int DECREMENTO = 31;
  public static final int error = 1;
  public static final int COMA = 51;
  public static final int NULO = 10;
  public static final int MODULO = 36;
  public static final int MENOS = 33;
  public static final int MENOR = 40;
  public static final int PAR_IZQ = 47;
  public static final int MAYOR = 42;
  public static final int ROMPER = 7;
  public static final int NO = 46;
  public static final int PUNTO = 53;
  public static final int LLAVE_DER = 50;
  public static final int VARIABLE = 2;
  public static final int MAYOR_IGUAL = 43;
  public static final int PARA = 6;
  public static final int RETORNAR = 9;
  public static final int DEFINIR = 27;
  public static final int TIPO_BOOLEANO = 14;
  public static final int MENOR_IGUAL = 41;
  public static final int TIPO_CADENA = 13;
  public static final int ENTRE = 35;
  public static final int A_FLOTANTE = 24;
  public static final int LITERAL_BOOLEANO = 16;
  public static final int MAS_ASIGNAR = 28;
  public static final int MAS = 32;
  public static final int TIPO_FLOTANTE = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VARIABLE",
  "FUNCION",
  "SI",
  "SINO",
  "PARA",
  "ROMPER",
  "CONTINUAR",
  "RETORNAR",
  "NULO",
  "TIPO_ENTERO",
  "TIPO_FLOTANTE",
  "TIPO_CADENA",
  "TIPO_BOOLEANO",
  "TIPO_RUNA",
  "LITERAL_BOOLEANO",
  "LITERAL_ENTERO",
  "LITERAL_FLOTANTE",
  "LITERAL_CADENA",
  "LITERAL_RUNA",
  "IDENTIFICADOR",
  "IMPRIMIR",
  "A_ENTERO",
  "A_FLOTANTE",
  "TIPO_DE",
  "ASIGNAR",
  "DEFINIR",
  "MAS_ASIGNAR",
  "MENOS_ASIGNAR",
  "INCREMENTO",
  "DECREMENTO",
  "MAS",
  "MENOS",
  "POR",
  "ENTRE",
  "MODULO",
  "MENOS_UNARIO",
  "IGUAL",
  "DIFERENTE",
  "MENOR",
  "MENOR_IGUAL",
  "MAYOR",
  "MAYOR_IGUAL",
  "Y",
  "O",
  "NO",
  "PAR_IZQ",
  "PAR_DER",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "COMA",
  "PUNTO_COMA",
  "PUNTO"
  };
}

